# Generated by Django 3.1.7 on 2021-05-18 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendship',
            name='fst_constraint',
        ),
        migrations.AlterField(
            model_name='friendship',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 17, 55, 11, 993682, tzinfo=utc)),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('first_user', 'second_user'), name='fst_constraint'),
        ),
    ]
